---
title: "Hw3"
author: Keshav Ramesh
format: pdf
editor: visual
---
```{r}
library(tidyverse)
library(palmerpenguins)

```

## Task 1 

### Question 1 

```{r}
read_csv("Data/data.txt")


```

The reason that we cannot use read_csv is that the data is delimited by something other than a comma or a tab. 


```{r}
data = read_csv2("Data/data.txt")
data
```


### Question 2


```{r}
data2 = read_delim("Data/data2.txt",
  delim = "6",
  col_types = cols(
    x = col_factor(),
    y = col_double(),
    z = col_character()
  )
  
)


data2
```

\newpage
## Task 2

### Question 1


```{r}
trailblazer <- read_csv("Data/trailblazer.csv")

glimpse(trailblazer)

head(trailblazer)

```

### Question 2

```{r}
trailblazer_longer = trailblazer %>%
  pivot_longer(!Player, names_to = "Game_Location", values_to = "Points") %>%
  separate(Game_Location, into = c("Game", "Location"), sep = "_")

head(trailblazer_longer, 5)
```

### Question 3

```{r}

trailblazer_points = trailblazer_longer %>%
  pivot_wider(names_from = Location, values_from = Points) %>%
  group_by(Player) %>%
  summarise(
    mean_home = mean(Home, na.rm = TRUE),
    mean_away = mean(Away, na.rm = TRUE),
    difference = mean_home - mean_away
  ) %>%
  arrange(desc(difference))

trailblazer_points



```












